### ISSUE TITLE
Set Open Loop Ramp Rate on all drive base motor controllers

### ISSUE THREAD

**Issue by AndrewIverson** [AusTINCANsProgrammingTeam/2022RobotCode#112]
Open loop ramp is the time it takes for the motor to go from 0 to 100% in open loop control, ie when the driver is driving the robot. Its wanted because it makes the robot "smoother" to control,  and reduces current draw during switching direction of spin(from full forward to full reverse).

https://codedocs.revrobotics.com/java/com/revrobotics/cansparkmax#setOpenLoopRampRate(double)

We have used .2 in the past as it seems to work, but we could experiment to see a nice value for the real robot.

**Comment by calvinwt** [comment]
It's been added in the MotorController class
