### ISSUE TITLE
Drive base Teleop command never scheduled

### ISSUE THREAD

**Issue by azvanderpas** [AusTINCANsProgrammingTeam/2022RobotCode#12]
https://github.com/AusTINCANsProgrammingTeam/2022RobotCode/blob/d5579f37169a2eb71b6de95731a66fed51a0eca2/src/main/java/frc/robot/RobotContainer.java#L39

We've create a command for the drive base, but it never gets scheduled. We either want to:
1. Schedule it manually in teleopPeriodic (Robot.java) OR
2. Remove the  DriveBaseTeleopCommand class and call arcadeDrive in DriveBaseSubsystem's periodic method

**Comment by tonyn10** [comment]
We set it as a default command in RobotContainer constructor
