### ISSUE TITLE
Code changes for rpi color sensor

### ISSUE THREAD

**Issue by caseyjbrotherton** [AusTINCANsProgrammingTeam/2022RobotCode#127]
If issue #125 continues, there is a workaround to use a raspberry pi to read from i2c and write the values to network tables

If that happens, there will need to be changes to cds. @Ariya3 @zainmfjavaid 

https://www.chiefdelphi.com/t/reliability-of-onboard-i2c-port-for-2022/399394/58

For details.

**Comment by AndrewIverson** [comment]
I think this needs to get its priority bumped to one of the most important things. We need to eliminate the I2C crashing and be confident that the I2C sensors are working for Austin Event coming up.

**Comment by caseyjbrotherton** [comment]
If I can take the mux home tonight, I should have the RPI part of it completed by Saturday.  Then on Saturday, the CDS team can code and test their side changes.  

This means mounting the pi and a network switch to the robot.

**Comment by AndrewIverson** [comment]
We have 5ish other mux's, so you can take some home to work with. I'll try to track down a network switch and do some prep work for mounting.

**Comment by caseyjbrotherton** [comment]
There is a small four port network switch in the drawers.  And barrel connectors to power ports.

**Comment by caseyjbrotherton** [comment]
Talked to Andrew. He has a raspberry pi pico inbound. When that arrives will try to use that.

**Comment by zainmfjavaid** [comment]
Color and proximity sensing should theoretically work through the Pico now. Still have to test to make sure.

**Comment by sarango2158** [comment]
Couldn't get this working, moving back to original setup for now.
