### ISSUE TITLE
CDs should prevent intake from running when full

### ISSUE THREAD

**Issue by caseyjbrotherton** [AusTINCANsProgrammingTeam/2022RobotCode#129]
When CDs has two cargo, it should prevent intake from running

( Likely better coded the other way...intake checks CDs for number of cargo )

**Comment by zainmfjavaid** [comment]
Right now, we have the intake run auto-eject whenever we have too many balls in the CDS. We could revert to how we used to do things (which simply didn't run auto-advance when there were too many balls) if that ends up being a better course of action.
