### ISSUE TITLE
Drive base controls are inverted

### ISSUE THREAD

**Issue by ModBoyex** [AusTINCANsProgrammingTeam/2022RobotCode#130]
On drive base test branch we have set arcadeDrive(-1* joystick, -1* joystick).
I think we have our motors left and right switched, or our invert is wrong.

Andrew made this issue btw, you can ask me questions

**Comment by caseyjbrotherton** [comment]
@calvinwt  and @tonyn10  tested this, and the controls seemed to work correctly. 

Is it possibly a problem with different controllers acting differently?

**Comment by sarango2158** [comment]
No longer reproducible. Drive controls worked properly at open house 3/10
