### ISSUE TITLE
CDS Changes for #125

### ISSUE THREAD

**Issue by AndrewIverson** [AusTINCANsProgrammingTeam/2022RobotCode#133]
#125  its possible always checking the color sensor is causing an issue, move the code out of periodic and into teleop periodic and autonomous periodic.

**Comment by sarango2158** [comment]
In the CDS branch @Ariya3 and @zainmfjavaid moved getSensorStatus out of periodic and into the execute() method of their CDSAutoAdvanceCommand and CDSBallManagementCommand (which is the default command of the subsystem). This may be an improvement, but worth checking how often this is called.

**Comment by caseyjbrotherton** [comment]
In testing, they were using a println, and this seemed to be still every 20ms.  

Should we try once every loop?  Reduce the frequency down to a max of every 40ms?

**Comment by sarango2158** [comment]
tied to runInterval in CDSBallManagement
