### ISSUE TITLE
CDS Color sensor thresold seems too low

### ISSUE THREAD

**Issue by azvanderpas** [AusTINCANsProgrammingTeam/2022RobotCode#136]
This value seems odd for the sensor range.

_Originally posted by @azvanderpas in https://github.com/AusTINCANsProgrammingTeam/2022RobotCode/pull/132#r819158529_

**Comment by sarango2158** [comment]
Did not see issues with the threshold in testing, but could test it in combo with issue #76

**Comment by azvanderpas** [comment]
To be more specific, I'd expect the color sensor proximity reading to be in the range between 400 to 2100 as shown in the APDS-9151 datasheet:
![image](https://user-images.githubusercontent.com/4372878/157473758-fcfeb36b-a894-4242-84bd-e2b596f9ca7f.png)

getProximity documentation says its range from 0 to 2047, however, so maybe its expected and that graph is incomplete?
