### ISSUE TITLE
CDS Sets idle mode on only one controller

### ISSUE THREAD

**Issue by AndrewIverson** [AusTINCANsProgrammingTeam/2022RobotCode#147]
The CDS is currently on setting the mode on line 61 CDSSubsystem.java `CDSWheelControllerOne.setIdleMode(IdleMode.kCoast);` the motor controllers are defaulted to coast after restoreFactoryDefaults is called. We can probably remove line 61.

**Comment by Ariya3** [comment]
deleted the line altogether
