### ISSUE TITLE
Have a way to enable/disable CDSBallManagementCommand and CDSAutoAdvance at compile time

### ISSUE THREAD

**Issue by AndrewIverson** [AusTINCANsProgrammingTeam/2022RobotCode#148]
During the match the auto ball management might not be behaving correctly or we want to disable the behavior for some reason or another. It should be possible to enable/disable the auto ejecting/sensing and moving of the Cargo in the CDS and fall back to manual control tied to running the intake.

**Comment by zainmfjavaid** [comment]
Added a way to do this pre-match. I'll work on making it so that this would also work during mid-match.

**Comment by sarango2158** [comment]
@zainmfjavaid updated this issue to be done at compile time. We'll add a longer-term goal for doing so on the fly
