### ISSUE TITLE
Make codebase simulatable

### ISSUE THREAD

**Issue by azvanderpas** [AusTINCANsProgrammingTeam/2022RobotCode#15]
Would be nice to be able to test code without a robot. 

Docs for setting up the simulator are here: https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/robot-simulation/introduction.html

**Comment by caseyjbrotherton** [comment]
@ModBoyex You have an open pull request.  can you please address the pull request modifications?
Then let's get that merged, and this issue closed.
