### ISSUE TITLE
Have a way to enable/disable CDSBallManagementCommand and CDSAutoAdvance during a match

### ISSUE THREAD

**Issue by sarango2158** [AusTINCANsProgrammingTeam/2022RobotCode#166]
During the match the auto ball management might not be behaving correctly or we want to disable the behavior for some reason or another. It should be possible to enable/disable the auto ejecting/sensing and moving of the Cargo in the CDS and fall back to manual control tied to running the intake. 

See issue #148 for initial implementation to disable at compile time

**Comment by sarango2158** [comment]
Thinking this would be nice to have fail over automatically if we detect the sensors are down

**Comment by zbrotherton** [comment]
This works very well with current code, closing this
