### ISSUE TITLE
[6] Add more autonomous paths

### ISSUE THREAD

**Issue by sarango2158** [AusTINCANsProgrammingTeam/2022RobotCode#199]
When we pair with alliances that have similar autonomous strategies, it would be nice to have more paths that accomplish the same goal (e.g., two-ball that uses a different cargo) so we can switch between them. Will also need a reasonable way to pick which path we're setting up, and instructions for where to place the robot for each path.

**Comment by azvanderpas** [comment]
4 Ball auto nominally working!
