### ISSUE TITLE
[7] Scouting app improvements

### ISSUE THREAD

**Issue by sarango2158** [AusTINCANsProgrammingTeam/2022RobotCode#200]
- Add a comment section
- Make climber area easier to see
- Make button location and size easier to use
- Arrange buttons to map the most frequently used to the easiest areas to reach on the tablet. For example, shooting buttons should be near where your thumbs can reach
- Add an "End" and "Submit" button
- Change wording for "Acquire"
- Change color

**Comment by zbrotherton** [comment]
Closing this, @caseyjbrotherton made changes addressing the majority of these
