### ISSUE TITLE
[8] Ball Management state machine

### ISSUE THREAD

**Issue by sarango2158** [AusTINCANsProgrammingTeam/2022RobotCode#201]
Use a state machine to drive the logic for ball management. See diagram
![PXL_20220323_003616504](https://user-images.githubusercontent.com/93295327/159599222-a63afbe0-8383-4543-b83a-a8cda545bb7a.jpg)

**Comment by azvanderpas** [comment]
#208 Initial implementation
#215 Adds additional path to move from Advance state to Eject in the case of a wrong color.
