### ISSUE TITLE
Add secondary climb camera

### ISSUE THREAD

**Issue by sarango2158** [AusTINCANsProgrammingTeam/2022RobotCode#23]
Climber will have a camera pointing directly upwards to align the robot. Will need to stream the feed to a dashboard for the drivers

**Comment by sarango2158** [comment]
We'll have the limelight and a drive camera on the robot. We may need to attach the drive camera to a servo and tilt it up physically for climb.

**Comment by sarango2158** [comment]
Possibly will make do without this, lowering to a stretch goal

**Comment by zbrotherton** [comment]
Do we have our camera ready in the shop? I can hopefully get this set up quickly if we do

**Comment by sarango2158** [comment]
We should re-evaluate this issue when we have a traversal climb @ModBoyex @loipiop224

**Comment by zbrotherton** [comment]
After actually being at a competition and climbing, I don't know how good a climb camera would be, and I'm also a little concerned about the act of changing cameras from code. (At the moment, I run a powershell command to start mpv when setting the driver station up)
