### ISSUE TITLE
If PID controller is unintilizied we should throw an error or something to make it apparent

### ISSUE THREAD

**Issue by AndrewIverson** [AusTINCANsProgrammingTeam/2022RobotCode#33]
https://github.com/AusTINCANsProgrammingTeam/2022RobotCode/blob/ab60cc198bbdfc5ff1ab8952528e955be3bc01b6/src/main/java/frc/robot/common/hardware/MotorController.java#L57

Comes from the issue Zane had, it wasn't apparent that the getPID() was returning something that wasn't a working PID controller.

**Comment by azvanderpas** [comment]
Duplicate to #13
