### ISSUE TITLE
Integer division likely cancels out gravity component of projectile calculation

### ISSUE THREAD

**Issue by azvanderpas** [AusTINCANsProgrammingTeam/2022RobotCode#38]
https://github.com/AusTINCANsProgrammingTeam/2022RobotCode/blob/85c9d208f1c986122bf16686a73a6b00fc7e33ae/src/main/java/frc/robot/subsystems/ShooterSubsystem.java#L125

The 1 / 2 of this line likely results as 0 since integer division will truncate any decimal/remainder. Either need to use 0.5 or at least one of the numbers needs to be a floating point literal, e.g. 1.0 / 2. 

@loipiop224 @Majorferguson21

**Comment by caseyjbrotherton** [comment]
@loipiop224 We had talked about this as well.  I believe you changed the 1/2, but don't see it in the code.

Seems like an easier one to make correct and merge, so we can close this issue.

**Comment by sarango2158** [comment]
Still an issue in latest for Shooter-Main(jim's) and ShooterTesting

**Comment by zbrotherton** [comment]
Closing this, we removed projectile prediction from the shooter's functionality and have moved to work with the lookup exclusively.
