### ISSUE TITLE
Store shooting parameters in a lookup table

### ISSUE THREAD

**Issue by sarango2158** [AusTINCANsProgrammingTeam/2022RobotCode#53]
Instead of calculating the different parameters of the shooter on the fly, store values for e.g. distance, flywheel RPM, hood angle in a lookup table to reference more quickly. Possibly add interpolation for in-between values.

**Comment by caseyjbrotherton** [comment]
If we store some known good values that we found through testing, we can then try to see if linear interpolation will help to fill out the  in between points:

https://en.wikipedia.org/wiki/Linear_interpolation
