### ISSUE TITLE
I think you want to call getBallCount() here instead of using the ballCount variable. Currently getBallCount() never gets run anywhere so ballCount will aways be 0.

### ISSUE THREAD

**Issue by zbrotherton** [AusTINCANsProgrammingTeam/2022RobotCode#60]
I think you want to call getBallCount() here instead of using the ballCount variable. Currently getBallCount() never gets run anywhere so ballCount will aways be 0.

_Originally posted by @azvanderpas in https://github.com/AusTINCANsProgrammingTeam/2022RobotCode/pull/46#discussion_r798129585_

**Comment by Ariya3** [comment]
got rid of the class cause we don't need it anymore
