### ISSUE TITLE
Shooter Sub Lines Not Needed

### ISSUE THREAD

**Issue by ModBoyex** [AusTINCANsProgrammingTeam/2022RobotCode#61]
Lines 41, 42, 51, and 52 are not needed

PID is not set and returns a null point exception causing a crash.

**Comment by sarango2158** [comment]
The PID and encoder for the cargo motor controller are not used regardless, so we should consider removing them.

**Comment by loipiop224** [comment]
> The PID and encoder for the cargo motor controller are not used regardless, so we should consider removing them.

ok
