### ISSUE TITLE
Modular subsystem layout does not account for inter-dependencies in commands

### ISSUE THREAD

**Issue by sarango2158** [AusTINCANsProgrammingTeam/2022RobotCode#66]
@azvanderpas 
Some commands now have dependencies on multiple subsystems. Modular subsystem does not account for this (looks at individual subsystems) and can disable subsystems that enabled commands depend on.

**Comment by zbrotherton** [comment]
Fixed this, currently on the ShooterTest branch, to be PR'd at a later time
