### ISSUE TITLE
Standardize HopperSubsystem to use MotorController

### ISSUE THREAD

**Issue by caseyjbrotherton** [AusTINCANsProgrammingTeam/2022RobotCode#8]
MotorController is a common class that standardizes some of the interactions with the CANsparkMax motor controllers.

The current HopperSubsystem is initializing and calling CANsparkMax directly.

Please reuse the MotorController class. 

This will make it easier to make changes across multiple subsystems, and make it easier for the team to read each other's code.

**Comment by zainmfjavaid** [comment]
Changed motor instantiation for Hopper and Intake
