### ISSUE TITLE
Eject a ball from the robot

### ISSUE THREAD

**Issue by sarango2158** [AusTINCANsProgrammingTeam/2022RobotCode#93]
Provide a way for the robot to eject a ball due to wrong color, too many, or a jam. Possible exits:

- Between singulator wheels and cargo belt
- Out the shooter
- (Least desirable) reverse out the intake

**Comment by zbrotherton** [comment]
I can make a simple shooter ejection mode, do we know if the singulator/cargo belt ejection is possible?

**Comment by zainmfjavaid** [comment]
In the CDS PR we just merged, there is an outtake command that can be used for ejecting. It's not the most ideal solution, but it's something.
