### ISSUE TITLE
Create switchable layouts for button bindings - test and competition

### ISSUE THREAD

**Issue by sarango2158** [AusTINCANsProgrammingTeam/2022RobotCode#95]
We should be able to quickly and easily change between a controller layout for testing and for competition. Testing layout should expose all our commands/functionality directly to easily troubleshoot. Competition layout should adhere to control scheme we agreed on at the meeting on 2/17

**Competition**
Driver:

- L Bumper - auto-shoot (while held)
- L Trigger - fender shot
- R Bumper - reverse intake
- R Trigger - forward intake
- L joystick - left drive
- R joystick - right drive 

Operator:

- Start button - enable climb
- R Bumper - reverse CDS
- R Trigger - forward CDS
- L joystick - climber control (up and down mapped to axis)

**Comment by sarango2158** [comment]
![PXL_20220218_015852052 MP](https://user-images.githubusercontent.com/93295327/154810012-ea7681cb-3602-4c5d-b353-3e84e84861ee.jpg)
![PXL_20220218_015856393 MP](https://user-images.githubusercontent.com/93295327/154810018-21253d05-f3ed-464c-af2f-5608bdf47918.jpg)

**Comment by azvanderpas** [comment]
I think the CDS/intake mappings are confusing. They should be mapped to trigger together, right @sarango2158?

@ModBoyex can you document here what your one controller test mapping is here?

**Comment by zbrotherton** [comment]
Due to driver requests, I have rebinded:
-Main shooter mode (currently TARMAC, LOW/AUTO will likely not be necessary/operable) to left trigger
-Secondary shooter mode (LOW at the moment) to left bumper
-Intake to the right trigger
-Outtake to the right bumper
